baseurl: https://sdfdsdfsdf-sf.netlify.app
title: Website
theme: hugo-theme-nix
languageCode: en-us
disqusShortname: your_disqus_shortname
menu:
  header:
    - name: post
      url: post
      weight: 0
    - name: about
      url: about
      weight: 1
params:
  About: Приветсвуем на нашем сайте! На нём мы разберём несколько пакетов на языке программирования R.
  Email: /inbox/
  Favicon: /favicon.ico
  GithubID: /LegionFenix
  HeaderHostname: site.ru
  HeaderUsername: Web
  Name: Главная страница
  ProfilePicture: /profile.jpg

